version: '3.8'
services:
  skripsi-wafi:
    container_name: skripsi_wafi
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/live/skripsi.wafi.web.id-0001/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/skripsi.wafi.web.id-0001/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - web_network
    depends_on:
      - skripsi-wafi
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge